pipeline {
    agent any

    environment {
        ANSIBLE_CONFIG = "ansible/ansible.cfg"
    }

    parameters {
        string(
            name: 'IP',
            description: 'Target IP'
        )
        string(
            name: 'USERNAME',
            description: 'SSH Username'
        )
        password(
            name: 'PASSWORD',
            description: 'SSH Password'
        )
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm: [
                    $class: 'GitSCM',
                    branches: scm.branches,
                    doGenerateSubmoduleConfigurations: false,
                    extensions: [[
                        $class: 'SubmoduleOption',
                        disableSubmodules: false,
                        parentCredentials: false,
                        recursiveSubmodules: true,
                        reference: '',
                        trackingSubmodules: false
                    ]],
                    submoduleCfg: [],
                    userRemoteConfigs: scm.userRemoteConfigs
                ]
            }
        }

        stage('Transfer Public SSH Key') {
            steps {
                echo 'Building..'
                sh "sshpass -p ${params.PASSWORD} ssh-copy-id -i ~/.ssh/id_rsa.pub ${params.USERNAME}@${params.IP}"
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying..'
            }
        }
    }
}