pipeline {
    agent any

    environment {
        ANSIBLE_CONFIG = "ansible/ansible.cfg"
    }

    parameters {
        string(
            name: 'IP',
            description: 'Target IP'
        )
        string(
            name: 'NAME',
            description: 'Raspberry Pi Name',
            defaultValue: 'rp0x'
        )
        string(
            name: 'USERNAME',
            defaultValue: 'pi',
            description: 'SSH Username'
        )
        password(
            name: 'PASSWORD',
            defaultValue: 'raspberry',
            description: 'SSH Password'
        )
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm: [
                    $class: 'GitSCM',
                    branches: scm.branches,
                    doGenerateSubmoduleConfigurations: false,
                    extensions: [[
                        $class: 'SubmoduleOption',
                        disableSubmodules: false,
                        parentCredentials: false,
                        recursiveSubmodules: true,
                        reference: '',
                        trackingSubmodules: false
                    ]],
                    submoduleCfg: [],
                    userRemoteConfigs: scm.userRemoteConfigs
                ]
            }
        }

        stage('Transfer Public SSH Key') {
            steps {
                sh "sshpass -p ${params.PASSWORD} ssh-copy-id -i ~/.ssh/id_rsa.pub ${params.USERNAME}@${params.IP}"
            }
        }
        stage('Add Raspberry to Ansible Host') {
            steps {
                sh "/home/pi/.local/bin/yaml_cli -f ansible/hosts.yml -s raspberry:hosts:${params.NAME}:ansible_host ${params.IP}"
                sh "/home/pi/.local/bin/yaml_cli -f ansible/hosts.yml -s raspberry:hosts:${params.NAME}:ansible_user ${params.USERNAME}"
            }
        }
    }
}