---
- hosts: raspberry

  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Download Docker installer
      get_url:
        url: https://get.docker.com/
        dest: ./get-docker.sh

    - name: Install Docker
      command: sudo sh ./get-docker.sh

    - name: Add Non-Root User to Docker Group
      command: sudo usermod -aG docker pi

    - name: Remove Installation Files
      file:
        src: ./get-docker.sh
        state: absent
