pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm: [
                    $class: 'GitSCM',
                    branches: scm.branches,
                    doGenerateSuboduleConfigurations: false,
                    extensions: [[
                        $class: 'SubmoduleOption',
                        disableSubmodules: false,
                        parentCredentials: false,
                        recursiveSubmodules: true,
                        reference: '',
                        trackingSubmodules: false
                    ]],
                    submoduleCfg: [],
                    userRemoteConfigs: scm.userRemoteConfigs
                ]
            }
        }

        stage('Setup') {
            input {
                message: "Target",
                parameters: {
                    name: 'TARGET',
                    choices: [
                        'Foo',
                        'Bar'
                    ],
                    $class: 'ChoiceParameterDefinition',
                    description: 'Target'
                }
            }
        }
        stage('Build') {
            steps {
                echo 'Building..'
                echo "Hello ${TARGET}"
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying..'
            }
        }
    }
}